language: node_js
node_js: node
sudo: false
services:
  - mongodb
script:
  - npm run build
  - npm run cover-memory
  - npm run cover-local
  - npm run cover-mongo
  - npm run lint
  - npm run duplication -- --limit=0.01
