version: 2
machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: node:8.11.3@sha256:38953a117b8f794426429314126af19ff17bbfaa5449c1829b9a8412b8ef4536
      - image: mongo:3.7.9@sha256:019f06f1fc9de0c7093ba517ff65ddc30f8aa22ff23e2e6f0ecd1ad2d0987263
      - image: redis:3.2.12@sha256:7d5d76e35b23a6907cf5877fd348ffea7212bb8bce56b2510e58d216462b98e2
    environment:
      - DOCKER_REPO_SLUG: learninglocker/xapi-statements
      - DOCKER_EMAIL: 0ryansmith1994@gmail.com
      - DOCKER_USERNAME: ryansmith94
      - NPM_CONFIG_LOGLEVEL: warn
      - WINSTON_CONSOLE_LEVEL: none
      - EXPRESS_PORT: 1337
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - run:
          name: Pruning Dependencies
          command: npm prune
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Compiling Code
          command: npm run build
      - run:
          name: Running tests
          command: npm run cover-ci
      - run:
          name: Linting Code
          command: npm run lint -- -c tslint.ci.json
      - run:
          name: Checking Code Duplication
          command: npm run duplication -- --limit 5
      - run:
          name: Docker Install
          command: |
            set -x
            DOCKER_VERSION="17.03.0-ce"
            curl -L -o /tmp/docker-$DOCKER_VERSION.tgz https://get.docker.com/builds/Linux/x86_64/docker-$DOCKER_VERSION.tgz
            tar -xz -C /tmp -f /tmp/docker-$DOCKER_VERSION.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Docker Build
          command: docker build -t "$DOCKER_REPO_SLUG" .
      - deploy:
          name: Semantic Release
          command: npm run semantic-release
